// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260429065955_UpdateWithRealBooks")]
    partial class UpdateWithRealBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Kristin Hannah",
                            AvailableCopies = 4,
                            CoverImagePath = "/images/book-covers/the-women.png",
                            DateAdded = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Historical Fiction",
                            ISBN = "978-1250178633",
                            PublicationYear = 2024,
                            Summary = "A powerful story of friendship and bravery that changed history. Women who served in the Vietnam War faced challenges that tested their courage and changed lives forever.",
                            Title = "The Women",
                            TotalCopies = 5
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Andrew Heywood",
                            AvailableCopies = 3,
                            CoverImagePath = "/images/book-covers/political-ideologies.png",
                            DateAdded = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Political Science",
                            ISBN = "978-1137606013",
                            PublicationYear = 2021,
                            Summary = "The most popular and comprehensive introduction to political ideologies, this best-selling textbook analyzes the major political ideologies of our time.",
                            Title = "Political Ideologies: An Introduction",
                            TotalCopies = 4
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Lucy Score",
                            AvailableCopies = 5,
                            CoverImagePath = "/images/book-covers/things-we-never-got-over.png",
                            DateAdded = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Romance",
                            ISBN = "978-1728282145",
                            PublicationYear = 2022,
                            Summary = "He's absolutely not falling for the good girl. A grumpy small-town romance from the Sunday Times and New York Times bestselling author.",
                            Title = "Things We Never Got Over",
                            TotalCopies = 6
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Hector Garcia and Francesc Miralles",
                            AvailableCopies = 4,
                            CoverImagePath = "/images/book-covers/ikigai.png",
                            DateAdded = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Self-Help",
                            ISBN = "978-0143130727",
                            PublicationYear = 2017,
                            Summary = "An international bestseller revealing the Japanese secret to finding purpose, meaning, and joy in life. Discover your reason for being.",
                            Title = "Ikigai: The Japanese Secret to a Long and Happy Life",
                            TotalCopies = 5
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Dr Carol S. Dweck",
                            AvailableCopies = 3,
                            CoverImagePath = "/images/book-covers/mindset.png",
                            DateAdded = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Psychology",
                            ISBN = "978-1780332000",
                            PublicationYear = 2017,
                            Summary = "World-renowned Stanford psychologist Carol Dweck shows how success can be influenced by how we think about our talents and abilities. The growth mindset creates motivation and productivity.",
                            Title = "Mindset: Changing the way you think to fulfil your potential",
                            TotalCopies = 4
                        },
                        new
                        {
                            BookId = 6,
                            Author = "James Clear",
                            AvailableCopies = 5,
                            CoverImagePath = "/images/book-covers/atomic-habits.png",
                            DateAdded = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Self-Help",
                            ISBN = "978-0735211292",
                            PublicationYear = 2018,
                            Summary = "Tiny changes, remarkable results. The phenomenal international bestseller with over 25 million copies sold. Transform your life with tiny changes in behavior, starting today.",
                            Title = "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
                            TotalCopies = 6
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BookRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookRatings");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("LoanDurationDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxBorrowableItems")
                        .HasColumnType("int");

                    b.Property<int>("MaxRenewals")
                        .HasColumnType("int");

                    b.Property<decimal>("OverduePenaltyPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ConfigId");

                    b.HasIndex("LibraryId")
                        .IsUnique();

                    b.ToTable("BorrowingConfigurations");

                    b.HasData(
                        new
                        {
                            ConfigId = 1,
                            LibraryId = 1,
                            LoanDurationDays = 14,
                            MaxBorrowableItems = 5,
                            MaxRenewals = 2,
                            OverduePenaltyPerDay = 0.50m
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FinePaid")
                        .HasColumnType("bit");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowingTransactions");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibraryId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LibraryId");

                    b.HasIndex("CreatedByUserId")
                        .IsUnique();

                    b.ToTable("LibraryProfiles");

                    b.HasData(
                        new
                        {
                            LibraryId = 1,
                            ContactEmail = "info@universitylibrary.edu",
                            ContactPhone = "555-0200",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibraryName = "University Central Library",
                            Location = "123 Campus Drive, Education City",
                            OperatingHours = "Mon-Fri: 8:00 AM - 8:00 PM, Sat-Sun: 10:00 AM - 6:00 PM"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "librarian@library.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Librarian",
                            Password = "$2a$11$iH5YB9NoY7WojumupQaaZuPrRxZcZfkDO2tQ.KU5yk2JXcDl4ZJ76",
                            PhoneNumber = "555-0100",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Librarian"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            Password = "$2a$11$26strlxj2B5fpNpt885DyO3mu6/sTFF1Mf4OzCFcbP1uzdDn0MCxe",
                            PhoneNumber = "555-0101",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Member"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            Password = "$2a$11$MErRrJwU90quVk4OyLZJt.KSwHMCDME6nYePa6NG6AyBq2mwuS19m",
                            PhoneNumber = "555-0102",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BookRating", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("BookRatings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Models.User", "User")
                        .WithMany("BookRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingConfiguration", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.LibraryProfile", "LibraryProfile")
                        .WithOne("Configuration")
                        .HasForeignKey("LibraryManagementSystem.Models.BorrowingConfiguration", "LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryProfile");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingTransaction", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Models.User", "User")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.User", "CreatedByUser")
                        .WithOne("LibraryProfile")
                        .HasForeignKey("LibraryManagementSystem.Models.LibraryProfile", "CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("BorrowingTransactions");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.User", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("BorrowingTransactions");

                    b.Navigation("LibraryProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
