// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260429055704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            DateAdded = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Programming",
                            ISBN = "978-0132350884",
                            PublicationYear = 2008,
                            Summary = "A comprehensive guide to writing clean, maintainable code with practical examples and best practices.",
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship",
                            TotalCopies = 5
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Thomas H. Cormen",
                            AvailableCopies = 2,
                            DateAdded = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Computer Science",
                            ISBN = "978-0262033848",
                            PublicationYear = 2009,
                            Summary = "Comprehensive text on algorithms covering a broad range of topics in depth.",
                            Title = "Introduction to Algorithms",
                            TotalCopies = 3
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Erich Gamma",
                            AvailableCopies = 4,
                            DateAdded = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            ISBN = "978-0201633610",
                            PublicationYear = 1994,
                            Summary = "Classic book on software design patterns for object-oriented programming.",
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software",
                            TotalCopies = 4
                        },
                        new
                        {
                            BookId = 4,
                            Author = "David Thomas",
                            AvailableCopies = 5,
                            DateAdded = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Programming",
                            ISBN = "978-0135957059",
                            PublicationYear = 2019,
                            Summary = "Your journey to mastery in software development with practical advice and best practices.",
                            Title = "The Pragmatic Programmer",
                            TotalCopies = 5
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Steve McConnell",
                            AvailableCopies = 2,
                            DateAdded = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Programming",
                            ISBN = "978-0735619678",
                            PublicationYear = 2004,
                            Summary = "A practical guide to software construction covering design, coding, debugging, and testing.",
                            Title = "Code Complete: A Practical Handbook of Software Construction",
                            TotalCopies = 3
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Eric Freeman",
                            AvailableCopies = 3,
                            DateAdded = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Software Engineering",
                            ISBN = "978-0596007126",
                            PublicationYear = 2004,
                            Summary = "A brain-friendly guide to design patterns with easy-to-understand explanations.",
                            Title = "Head First Design Patterns",
                            TotalCopies = 3
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Martin Fowler",
                            AvailableCopies = 4,
                            DateAdded = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Programming",
                            ISBN = "978-0134757599",
                            PublicationYear = 2018,
                            Summary = "Essential guide to improving code structure and design without changing its behavior.",
                            Title = "Refactoring: Improving the Design of Existing Code",
                            TotalCopies = 4
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            DateAdded = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Professional Development",
                            ISBN = "978-0137081073",
                            PublicationYear = 2011,
                            Summary = "Practical advice for becoming a true professional software developer.",
                            Title = "The Clean Coder: A Code of Conduct for Professional Programmers",
                            TotalCopies = 3
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Kyle Simpson",
                            AvailableCopies = 5,
                            DateAdded = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Web Development",
                            ISBN = "978-1449335588",
                            PublicationYear = 2014,
                            Summary = "Deep dive into JavaScript's scope and closures mechanisms.",
                            Title = "You Don't Know JS: Scope & Closures",
                            TotalCopies = 5
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Marijn Haverbeke",
                            AvailableCopies = 4,
                            DateAdded = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Web Development",
                            ISBN = "978-1593279509",
                            PublicationYear = 2018,
                            Summary = "A modern introduction to programming with JavaScript.",
                            Title = "Eloquent JavaScript",
                            TotalCopies = 4
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BookRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookRatings");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingConfiguration", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("LoanDurationDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxBorrowableItems")
                        .HasColumnType("int");

                    b.Property<int>("MaxRenewals")
                        .HasColumnType("int");

                    b.Property<decimal>("OverduePenaltyPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ConfigId");

                    b.HasIndex("LibraryId")
                        .IsUnique();

                    b.ToTable("BorrowingConfigurations");

                    b.HasData(
                        new
                        {
                            ConfigId = 1,
                            LibraryId = 1,
                            LoanDurationDays = 14,
                            MaxBorrowableItems = 5,
                            MaxRenewals = 2,
                            OverduePenaltyPerDay = 0.50m
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FinePaid")
                        .HasColumnType("bit");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowingTransactions");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibraryId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperatingHours")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LibraryId");

                    b.HasIndex("CreatedByUserId")
                        .IsUnique();

                    b.ToTable("LibraryProfiles");

                    b.HasData(
                        new
                        {
                            LibraryId = 1,
                            ContactEmail = "info@universitylibrary.edu",
                            ContactPhone = "555-0200",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibraryName = "University Central Library",
                            Location = "123 Campus Drive, Education City",
                            OperatingHours = "Mon-Fri: 8:00 AM - 8:00 PM, Sat-Sun: 10:00 AM - 6:00 PM"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "librarian@library.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Librarian",
                            Password = "$2a$11$kd.lRYWl3l0aFlSnrc1TpOh1RssVVoirOtqVG2XGT5aHT27T.WBRC",
                            PhoneNumber = "555-0100",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Librarian"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            Password = "$2a$11$2JS5LDKFgcX2jjRsVrJhuekxnhp.qIF6eNxEt5V.PYpwANK7XinGG",
                            PhoneNumber = "555-0101",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Member"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            Password = "$2a$11$/EI9VrTGKQ1zpiwX26fCCuDJb3djSy.zhBeA/AgXsrssY3xbTc0Se",
                            PhoneNumber = "555-0102",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BookRating", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("BookRatings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Models.User", "User")
                        .WithMany("BookRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingConfiguration", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.LibraryProfile", "LibraryProfile")
                        .WithOne("Configuration")
                        .HasForeignKey("LibraryManagementSystem.Models.BorrowingConfiguration", "LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryProfile");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowingTransaction", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Models.User", "User")
                        .WithMany("BorrowingTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.User", "CreatedByUser")
                        .WithOne("LibraryProfile")
                        .HasForeignKey("LibraryManagementSystem.Models.LibraryProfile", "CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("BorrowingTransactions");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.LibraryProfile", b =>
                {
                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.User", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("BorrowingTransactions");

                    b.Navigation("LibraryProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
